### ISSUE TITLE
DllNotFoundException: agoraSdkCWrapper

### ISSUE THREAD

**Issue by kkarannn** [AgoraIO/Video-Call-for-Mobile-Gaming#6]
On pressing join button this shows up.
clicking once again it starts hello scene but on phone it crashes on first click

**Comment by zhangtao1104** [comment]
Have you put the sdk plugin into the demo ? @kkarannn

**Comment by vinayak-vc** [comment]
![image](https://user-images.githubusercontent.com/47971927/59661497-92916680-91c8-11e9-9b44-54abb8d451b0.png)


Hii I have done it like this 

but still getting error @zhangtao1104 
Thanks in advance

**Comment by zhangtao1104** [comment]
You need to build the project and run the demo in android phone or iphone.

**Comment by vinayak-vc** [comment]
this will not work in Edit even though I have attached the WEBCAM?

**Comment by vinayak-vc** [comment]
And how do I play the video on Raw Image or on Image instead of the cube?

Thanks.

**Comment by zhangtao1104** [comment]
Yes , because you do not put the win plugin into the demo. If you want to get the win plugin ,you can contact our customer support. This is our Official website. https://www.agora.io/cn/

**Comment by zhangtao1104** [comment]
You can read the source code in VideoSurface.cs.The only thing you need to do is attach the Texture2D to the gameObject which you want to render the video.

**Comment by vinayak-vc** [comment]
> You can read the source code in VideoSurface.cs.The only thing you need to do is attach the Texture2D to the gameObject which you want to render the video.

Thanks man!!!

**Comment by vinayak-vc** [comment]
> Yes, because you do not put the win plugin into the demo. If you want to get the win plugin ,you can contact our customer support. This is our Official website. https://www.agora.io/cn/

Okay Thanks!!

**Comment by zhangtao1104** [comment]
It is all right.

**Comment by vinayak-vc** [comment]
Hii @zhangtao1104 

I successfully achieved the live video sharing but I want to Cast the screen
can you help? 
if you can give any insights.
Thanks

**Comment by GreenArrowRepo** [comment]
This is not helpful !! 
It is not working in mobile phone! 

Executed it in phone still not able to see the video !!!!

**Comment by GreenArrowRepo** [comment]
@vinayak-vc  did the solution work ?? given by @zhangtao1104 

@vinayak-vc  i don't see your comment that it is solved.

**Comment by zhangtao1104** [comment]
Ok, please wait a minute, I will help you ,it will work well.

**Comment by zhangtao1104** [comment]
@GreenArrowRepo

**Comment by zhangtao1104** [comment]
https://docs.agora.io/en/Interactive%20Gaming/game_unity_android_video?platform=Unity_(Android) Please run the demo according to the quickStart guide. @GreenArrowRepo

**Comment by kkarannn** [comment]
@zhangtao1104 I have agoraSdkCWrapper from the sdk plugin from assetstore. Still getting DllNotFoundException: agoraSdkCWrapper error on PC and video not working on mobile.

Where do i have to place it in the project?

**Comment by zhangtao1104** [comment]
<img width="1258" alt="WeChata567de2c5ac4bbaa699b604ae20fec86" src="https://user-images.githubusercontent.com/22463683/67565430-01bf2e80-f758-11e9-8b72-8579588088ad.png">
<img width="1594" alt="WeChat39b56c6aa024b668e6be25c3e72a11cf" src="https://user-images.githubusercontent.com/22463683/67565434-02f05b80-f758-11e9-8378-73acc2cc6638.png">

**Comment by zhangtao1104** [comment]
Do you have  x86 and x86_64 plugin in your project?

This is for windows, Please confirm it.

**Comment by zhangtao1104** [comment]
<img width="2496" alt="WeChatefa07a477e5f69dc1f6e24200c550e98" src="https://user-images.githubusercontent.com/22463683/67565698-a0e42600-f758-11e9-86d2-69f3ef17b2c1.png">

**Comment by zhangtao1104** [comment]
You can integrate according to readme's instructions, which are explained in great detail

**Comment by kkarannn** [comment]
Got it working!! Thanks. 
How can I use sharescreen feature from agora to share my screen instead of camera??

**Comment by zhangtao1104** [comment]
You can call setExternalVideoSource first. It allows you to capture your own video frames and stop the SDK's camera capture.

Then you need to call pushExternalVideoFrame every video frame  to push your own video frame to agora sdk.

**Comment by zhangtao1104** [comment]
You can integrate this according to our offical documents,it will help you a lot.

**Comment by zhangtao1104** [comment]
https://docs-preview.agoralab.co/en/Interactive%20Gaming/game_unity?platform=Unity&versionId=81465890-f18b-11e9-8bb5-37fc243d5a73

**Comment by GreenArrowRepo** [comment]
@zhangtao1104  Hello,
Thanks for the help.

I was able to solve the issue.

**Comment by GreenArrowRepo** [comment]
@zhangtao1104  

I have set video profile to 'command mode' and client role as 'broadcaster'.
Out of all the users who are in video chat one user will broadcast and other will see.

What i want to do is that the broadcaster and the audience should be able to draw on screen using a color pencil and all should be able to see in real time.

Is is possible in agora unity sdk ? Check this [video ](https://www.youtube.com/watch?v=mYYLXaIl1Hc)for more clarity.
P.S : We are not looking for AR functionality, we are only looking for drawing broadcast to all users using agora.

Please revert when you see this.

**Comment by zhangtao1104** [comment]
For agora, i think this question is that wheather agora unity video sdk can transfer the data stream, right? 
@GreenArrowRepo

**Comment by GreenArrowRepo** [comment]
Yes @zhangtao1104 correct.

**Comment by zhangtao1104** [comment]
Yes, agora video sdk can transfer data stream, you can see the api named createDataStream and sendStreamMessage.

**Comment by zhangtao1104** [comment]
@GreenArrowRepo

**Comment by GreenArrowRepo** [comment]
Ok Thanks  @zhangtao1104 i will look into that !!!

**Comment by GreenArrowRepo** [comment]
Hi @zhangtao1104  i could not find the createDataStream api in [unity API](https://docs.agora.io/en/Interactive%20Gaming/game_unity?platform=Unity)

**Comment by zhangtao1104** [comment]
The api named CreateDataStream , SendStreamMessage.Please find again，there should be these apis. @GreenArrowRepo

**Comment by kkarannn** [comment]
I've got video calling working on android on a custom video plane with videosurface.cs on it.
But can't figure it out on iOS. I can only see device front cam video on both the devices..
I am not allowing a new gameObject with uid name to be created..

Please Help me figure out how to enable video connection between iOS devices.

![AgoraHeriarchy](https://user-images.githubusercontent.com/40266086/68384051-c6235c00-017c-11ea-8ba5-f90968137ccf.PNG)
![AgoraCode](https://user-images.githubusercontent.com/40266086/68384055-c7548900-017c-11ea-95b9-c9520a8c277f.PNG)

**Comment by kkarannn** [comment]
onUserJoined is not called when another user joins..

**Comment by LuizPelegrini** [comment]
> onUserJoined is not called when another user joins..

I can't even get the callback OnJoinChannelSuccess called. It is so frustrating...

**Comment by zhangtao1104** [comment]
Is there some error log output in console when you joinChannel? If it is not,

Do you input your appId in SceneHome.unity?



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AgoraIO/Video-Call-for-Mobile-Gaming"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月11日(星期五) 中午11:29
收件人:&nbsp;"AgoraIO/Video-Call-for-Mobile-Gaming"<Video-Call-for-Mobile-Gaming@noreply.github.com&gt;;
抄送:&nbsp;"White"<1831369722@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [AgoraIO/Video-Call-for-Mobile-Gaming] DllNotFoundException: agoraSdkCWrapper (#6)





  
onUserJoined is not called when another user joins..
  
I can't even get the callback OnJoinChannelSuccess called. It is so frustrating...

**Comment by LuizPelegrini** [comment]
@zhangtao1104 I managed to figure it out, for some reason the first appId copied from Agora dashboard was not working. I had to create a new project with a new AppId and use the new one. Now I can play the demo scene with no issues.

thank you!

**Comment by zhangtao1104** [comment]
I think you open the encryption on the first appId, so it was not working.
If you open the encryption on the appId, you need to joinChannel with token, otherwise you joinChannel fail.


You can search the document of token in agora website.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AgoraIO/Video-Call-for-Mobile-Gaming"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月11日(星期五) 中午12:58
收件人:&nbsp;"AgoraIO/Video-Call-for-Mobile-Gaming"<Video-Call-for-Mobile-Gaming@noreply.github.com&gt;;
抄送:&nbsp;"White"<1831369722@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [AgoraIO/Video-Call-for-Mobile-Gaming] DllNotFoundException: agoraSdkCWrapper (#6)





 
@zhangtao1104 I managed to figure it out, for some reason the first appId copied from Agora dashboard was not working. I had to create a new project with a new AppId and use the new one. Now I can play the demo scene with no issues.
 
thank you!

**Comment by LuizPelegrini** [comment]
Thank you for the clarification @zhangtao1104 I'll keep that in mind
